# config-repo-server
Config Server repository for micro service
        spring:
            profiles:cloud-config
         eureka:
             client:
                  register-with-eureka: true
                  fatch-registry: true
                  service-url:
                          defaultZone: http://localhost:8761/eureka/
            instance:
                  hostname:localhost
              
